##########################################
### SAMPLE
##########################################

# User
userId: "<samplify userId>"  # e.g. userid: "kolart"
userEmail: "<userEmail>"     # e.g. userEmail: "kolart@uw.edu"

# Sample
sampleDirectory: "<full path to sample directory>"    # e.g. sampleDirectory: "/net/nwgc/vol1/data/processed/samples/123456/WHOLE_GENOME"
sampleId: <samplify sampleId>  # e.g sampleId: 123456

# Reference Genome
referenceGenome: "<full path to reference genome fasta>"    # e.g. referenceGenome: "/net/nwgc/vol1/references/human/grc38/genome/pacbio/human_GRCh38_no_alt_analysis_set.fasta"
targetListFile: "<full path to target .list file>"    # e.g. targetListFile: "/net/nwgc/vol1/references/human/grc38/genome/pacbio/human_GRCh38_no_alt_analysis_set.fasta"
dbSnp: "<full path to dbSnp file>"    # e.g. dbSnp: "/net/nwgc/vol1/references/human/grc38/genome/pacbio/human_GRCh38_no_alt_analysis_set.fasta"

# Bam  
bam: "<full path to the bam file from which to call variants>"  # e.g.  bam: /net/nwgc/vol1/home/kolart/pacbio_merged_test.bam   


##########################################
### RabbitMQ
##########################################
rabbitHost: "<name of host for rabbitMQ>"				#e.g rabbitHost: "burnet"
registration_url: "<url to send rabbit message to>"		#e.g.registration_url: "http://burnet.gs.grid.washington.edu/samplify/RegisterPacBioMapMergeQCCompletion"
